/**
 * ChainHub Database Seed
 * Version: 1.1 (Repair — groupId added)
 * Generated by: BA-02 (Schema-agent)
 *
 * Opretter realistisk testdata:
 * - 1 organisation (tandlægekæde)
 * - 1 gruppe
 * - 2 selskaber (holdingselskab + 1 klinik)
 * - 3 brugere (owner, admin, readonly)
 * - 5 kontrakter (ejeraftale, lejekontrakt, ansættelse, leverandør, forsikring)
 * - 2 personer (ejer, ansat)
 */

import {
  PrismaClient,
  UserRole,
  UserScope,
  ContractSystemType,
  ContractStatus,
  SensitivityLevel,
  DeadlineType,
  VersionSource,
  MetricType,
  PeriodType,
  MetricSource,
  Prioritet,
  SagsType,
  CaseStatus,
  EmploymentType,
} from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting ChainHub database seed...');

  // ==================== ORGANIZATION ====================
  const organization = await prisma.organization.create({
    data: {
      id: 'org-chainhub-demo-001',
      name: 'Tandlægekæden ApS',
      cvr: '12345678',
      plan: 'business',
      chainStructure: true,
      createdBy: null,
    },
  });
  console.log(`✅ Organization created: ${organization.name}`);

  // ==================== GROUP ====================
  const group = await prisma.group.create({
    data: {
      id: 'group-main-001',
      organizationId: organization.id,
      name: 'Tandlægekæden Koncern',
      description: 'Primær koncerngruppe',
      createdBy: null,
    },
  });
  console.log(`✅ Group created: ${group.name}`);

  // ==================== USERS ====================
  const userOwner = await prisma.user.create({
    data: {
      id: 'user-owner-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'lars.jensen@tandlaegekaden.dk',
      name: 'Lars Jensen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userAdmin = await prisma.user.create({
    data: {
      id: 'user-admin-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'maria.nielsen@tandlaegekaden.dk',
      name: 'Maria Nielsen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userReadonly = await prisma.user.create({
    data: {
      id: 'user-readonly-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'peter.hansen@tandlaegekaden.dk',
      name: 'Peter Hansen',
      avatarUrl: null,
      microsoftId: null,
    },
  });
  console.log(`✅ Users created: ${userOwner.name}, ${userAdmin.name}, ${userReadonly.name}`);

  // ==================== USER ROLE ASSIGNMENTS ====================
  await prisma.userRoleAssignment.createMany({
    data: [
      {
        id: 'role-owner-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userOwner.id,
        role: UserRole.GROUP_OWNER,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-admin-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userAdmin.id,
        role: UserRole.GROUP_ADMIN,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-readonly-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userReadonly.id,
        role: UserRole.GROUP_READONLY,
        scope: UserScope.ASSIGNED,
        companyIds: ['company-klinik-001'],
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ User roles assigned');

  // ==================== COMPANIES ====================
  const companyHolding = await prisma.company.create({
    data: {
      id: 'company-holding-001',
      organizationId: organization.id,
      groupId: group.id,
      name: 'Tandlægekæden Holding ApS',
      cvr: '87654321',
      legalForm: 'ApS',
      address: 'Kongevejen 1',
      city: 'København',
      zipCode: '1000',
      country: 'DK',
      isHolding: true,
      chainStructure: true,
      createdBy: userOwner.id,
    },
  });

  const companyKlinik = await prisma.company.create({
    data: {
      id: 'company-klinik-001',
      organizationId: organization.id,
      groupId: group.id,
      name: 'Klinik Nørrebro ApS',
      cvr: '11223344',
      legalForm: 'ApS',
      address: 'Nørrebrogade 42',
      city: 'København N',
      zipCode: '2200',
      country: 'DK',
      isHolding: false,
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Companies created: ${companyHolding.name}, ${companyKlinik.name}`);

  // ==================== COMPANY OWNERSHIP ====================
  await prisma.companyOwnership.create({
    data: {
      id: 'ownership-001',
      organizationId: organization.id,
      parentCompanyId: companyHolding.id,
      childCompanyId: companyKlinik.id,
      ownershipPct: 100,
      votingPct: 100,
      ownershipType: 'DIREKTE',
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Company ownership created');

  // ==================== PERSONS ====================
  const personEjer = await prisma.person.create({
    data: {
      id: 'person-ejer-001',
      organizationId: organization.id,
      firstName: 'Lars',
      lastName: 'Jensen',
      email: 'lars.jensen@privat.dk',
      phone: '+45 20 20 20 20',
      createdBy: userOwner.id,
    },
  });

  const personAnsat = await prisma.person.create({
    data: {
      id: 'person-ansat-001',
      organizationId: organization.id,
      firstName: 'Anna',
      lastName: 'Christensen',
      email: 'anna.christensen@tandlaegekaden.dk',
      phone: '+45 30 30 30 30',
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Persons created: ${personEjer.firstName} ${personEjer.lastName}, ${personAnsat.firstName} ${personAnsat.lastName}`);

  // ==================== COMPANY PERSONS ====================
  await prisma.companyPerson.createMany({
    data: [
      {
        id: 'cp-ejer-holding-001',
        organizationId: organization.id,
        companyId: companyHolding.id,
        personId: personEjer.id,
        role: 'direktør',
        title: 'Administrerende Direktør',
        employmentType: EmploymentType.FUNKTIONAER,
        startDate: new Date('2020-01-01'),
        isPrimary: true,
        createdBy: userOwner.id,
      },
      {
        id: 'cp-ansat-klinik-001',
        organizationId: organization.id,
        companyId: companyKlinik.id,
        personId: personAnsat.id,
        role: 'tandlæge',
        title: 'Specialtandlæge',
        employmentType: EmploymentType.FUNKTIONAER,
        startDate: new Date('2022-03-01'),
        isPrimary: true,
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ Company persons created');

  // ==================== CONTRACTS ====================
  const contractEjeraftale = await prisma.contract.create({
    data: {
      id: 'contract-ejeraftale-001',
      organizationId: organization.id,
      companyId: companyHolding.id,
      systemType: ContractSystemType.EJERAFTALE,
      displayName: 'Ejeraftale — Tandlægekæden Holding ApS',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.FORTROLIG,
      deadlineType: DeadlineType.INGEN,
      versionSource: VersionSource.INTERNT,
      signedDate: new Date('2020-01-15'),
      effectiveDate: new Date('2020-01-15'),
      counterpartyName: 'Lars Jensen (privat)',
      createdBy: userOwner.id,
    },
  });

  const contractLejekontrakt = await prisma.contract.create({
    data: {
      id: 'contract-lejekontrakt-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      systemType: ContractSystemType.LEJEKONTRAKT_ERHVERV,
      displayName: 'Erhvervslejekontrakt — Nørrebrogade 42',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.STANDARD,
      deadlineType: DeadlineType.OPERATIONEL,
      versionSource: VersionSource.BRANCHESTANDARD,
      signedDate: new Date('2022-01-01'),
      effectiveDate: new Date('2022-02-01'),
      expiryDate: new Date('2027-01-31'),
      noticePeriodDays: 180,
      counterpartyName: 'Nørrebro Ejendomme A/S',
      totalValue: 72000,
      currency: 'DKK',
      createdBy: userOwner.id,
    },
  });

  const contractAnsaettelse = await prisma.contract.create({
    data: {
      id: 'contract-ansaettelse-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      systemType: ContractSystemType.ANSAETTELSE_FUNKTIONAER,
      displayName: 'Ansættelseskontrakt — Anna Christensen',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.FORTROLIG,
      deadlineType: DeadlineType.INGEN,
      versionSource: VersionSource.INTERNT,
      signedDate: new Date('2022-02-15'),
      effectiveDate: new Date('2022-03-01'),
      noticePeriodDays: 90,
      createdBy: userOwner.id,
    },
  });

  const contractLeverandoer = await prisma.contract.create({
    data: {
      id: 'contract-leverandoer-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      systemType: ContractSystemType.LEVERANDOERKONTRAKT,
      displayName: 'Leverandøraftale — Dental Supplies DK',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.STANDARD,
      deadlineType: DeadlineType.OPERATIONEL,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      signedDate: new Date('2023-01-01'),
      effectiveDate: new Date('2023-01-01'),
      expiryDate: new Date('2025-12-31'),
      noticePeriodDays: 60,
      counterpartyName: 'Dental Supplies DK ApS',
      totalValue: 180000,
      currency: 'DKK',
      createdBy: userOwner.id,
    },
  });

  const contractForsikring = await prisma.contract.create({
    data: {
      id: 'contract-forsikring-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      systemType: ContractSystemType.FORSIKRING,
      displayName: 'Erhvervsansvarsforsikring 2024',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.ABSOLUT,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      signedDate: new Date('2024-01-01'),
      effectiveDate: new Date('2024-01-01'),
      expiryDate: new Date('2024-12-31'),
      autoRenewal: true,
      counterpartyName: 'Tryg Forsikring A/S',
      totalValue: 24000,
      currency: 'DKK',
      createdBy: userOwner.id,
    },
  });

  console.log(`✅ Contracts created: ${contractEjeraftale.displayName}, ${contractLejekontrakt.displayName}, ${contractAnsaettelse.displayName}, ${contractLeverandoer.displayName}, ${contractForsikring.displayName}`);

  // ==================== FINANCIAL METRICS ====================
  await prisma.financialMetric.createMany({
    data: [
      {
        id: 'metric-omsaetning-2023',
        organizationId: organization.id,
        companyId: companyKlinik.id,
        metricType: MetricType.OMSAETNING,
        value: 4200000,
        currency: 'DKK',
        periodType: PeriodType.HELAAR,
        periodYear: 2023,
        source: MetricSource.REVIDERET,
        createdBy: userOwner.id,
      },
      {
        id: 'metric-ebitda-2023',
        organizationId: organization.id,
        companyId: companyKlinik.id,
        metricType: MetricType.EBITDA,
        value: 840000,
        currency: 'DKK',
        periodType: PeriodType.HELAAR,
        periodYear: 2023,
        source: MetricSource.REVIDERET,
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ Financial metrics created');

  // ==================== CASE ====================
  const demoCase = await prisma.case.create({
    data: {
      id: 'case-demo-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      title: 'Fornyelse af lejekontrakt Nørrebrogade 42',
      description: 'Lejekontrakt udløber jan 2027 — skal forhandles inden jul 2026.',
      sagsType: SagsType.KONTRAKT,
      status: CaseStatus.NY,
      sensitivity: SensitivityLevel.INTERN,
      prioritet: Prioritet.HOEJ,
      deadlineDate: new Date('2026-07-01'),
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Case created: ${demoCase.title}`);

  // ==================== ALERTS ====================
  await prisma.alert.create({
    data: {
      id: 'alert-lejekontrakt-001',
      organizationId: organization.id,
      companyId: companyKlinik.id,
      contractId: contractLejekontrakt.id,
      alertType: 'OPSIGELSE',
      title: 'Opsigelsesdato nærmer sig — Lejekontrakt Nørrebrogade 42',
      description: 'Kontrakten kan opsiges senest 1. juli 2026 for at undgå automatisk forlængelse.',
      dueDate: new Date('2026-07-01'),
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Alerts created');

  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });