/**
 * ChainHub Database Seed
 * Version: 1.0
 * Generated by: BA-02 (Schema-agent)
 * 
 * Opretter realistisk testdata:
 * - 1 organisation (tandlægekæde)
 * - 2 selskaber (holdingselskab + 1 klinik)
 * - 3 brugere (owner, admin, readonly)
 * - 5 kontrakter (ejeraftale, lejekontrakt, ansættelse, leverandør, forsikring)
 * - 2 personer (ejer, ansat)
 */

import { PrismaClient, UserRole, UserScope, ContractSystemType, ContractStatus, SensitivityLevel, DeadlineType, VersionSource, MetricType, PeriodType, MetricSource, Prioritet, SagsType, CaseStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting ChainHub database seed...');

  // ==================== ORGANIZATION ====================
  const organization = await prisma.organization.create({
    data: {
      id: 'org-chainhub-demo-001',
      name: 'Tandlægekæden ApS',
      cvr: '12345678',
      plan: 'business',
      chainStructure: true,
      createdBy: null, // self-signup
    },
  });
  console.log(`✅ Organization created: ${organization.name}`);

  // ==================== USERS ====================
  const userOwner = await prisma.user.create({
    data: {
      id: 'user-owner-001',
      organizationId: organization.id,
      email: 'lars.jensen@tandlaegekaden.dk',
      name: 'Lars Jensen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userAdmin = await prisma.user.create({
    data: {
      id: 'user-admin-001',
      organizationId: organization.id,
      email: 'maria.nielsen@tandlaegekaden.dk',
      name: 'Maria Nielsen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userReadonly = await prisma.user.create({
    data: {
      id: 'user-readonly-001',
      organizationId: organization.id,
      email: 'peter.hansen@tandlaegekaden.dk',
      name: 'Peter Hansen',
      avatarUrl: null,
      microsoftId: null,
    },
  });
  console.log(`✅ Users created: ${userOwner.name}, ${userAdmin.name}, ${userReadonly.name}`);

  // ==================== USER ROLE ASSIGNMENTS ====================
  await prisma.userRoleAssignment.createMany({
    data: [
      {
        id: 'role-owner-001',
        organizationId: organization.id,
        userId: userOwner.id,
        role: UserRole.GROUP_OWNER,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-admin-001',
        organizationId: organization.id,
        userId: userAdmin.id,
        role: UserRole.GROUP_ADMIN,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-readonly-001',
        organizationId: organization.id,
        userId: userReadonly.id,
        role: UserRole.GROUP_READONLY,
        scope: UserScope.ASSIGNED,
        companyIds: ['company-klinik-001'],
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ User roles assigned');

  // ==================== COMPANIES ====================
  const holdingCompany = await prisma.company.create({
    data: {
      id: 'company-holding-001',
      organizationId: organization.id,
      name: 'Tandlægekæden Holding ApS',
      cvr: '12345678',
      companyType: 'ApS',
      address: 'Hovedgaden 1',
      city: 'København',
      postalCode: '1000',
      foundedDate: new Date('2018-01-15'),
      status: 'aktiv',
      notes: 'Holdingselskab for tandlægekæden',
      createdBy: userOwner.id,
    },
  });

  const klinikCompany = await prisma.company.create({
    data: {
      id: 'company-klinik-001',
      organizationId: organization.id,
      name: 'Tandlægeklinikken Østerbro ApS',
      cvr: '87654321',
      companyType: 'ApS',
      address: 'Østerbrogade 50',
      city: 'København Ø',
      postalCode: '2100',
      foundedDate: new Date('2020-03-01'),
      status: 'aktiv',
      notes: 'Klinik på Østerbro - co-owned med partner',
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Companies created: ${holdingCompany.name}, ${klinikCompany.name}`);

  // ==================== PERSONS ====================
  const personOwner = await prisma.person.create({
    data: {
      id: 'person-owner-001',
      organizationId: organization.id,
      firstName: 'Lars',
      lastName: 'Jensen',
      email: 'lars.jensen@tandlaegekaden.dk',
      phone: '+45 12 34 56 78',
      notes: 'Hovedejer af kæden',
      createdBy: userOwner.id,
    },
  });

  const personEmployee = await prisma.person.create({
    data: {
      id: 'person-employee-001',
      organizationId: organization.id,
      firstName: 'Anna',
      lastName: 'Pedersen',
      email: 'anna.pedersen@tandlaegekaden.dk',
      phone: '+45 87 65 43 21',
      notes: 'Klinikassistent',
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Persons created: ${personOwner.firstName} ${personOwner.lastName}, ${personEmployee.firstName} ${personEmployee.lastName}`);

  // ==================== OWNERSHIP ====================
  await prisma.ownership.create({
    data: {
      id: 'ownership-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      ownerPersonId: personOwner.id,
      ownershipPct: 60.00,
      shareClass: 'A-anparter',
      effectiveDate: new Date('2020-03-01'),
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Ownership structure created');

  // ==================== COMPANY PERSONS ====================
  await prisma.companyPerson.create({
    data: {
      id: 'cp-employee-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      personId: personEmployee.id,
      role: 'ansat',
      employmentType: 'funktionær',
      startDate: new Date('2021-06-01'),
      anciennityStart: new Date('2021-06-01'),
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Company-person relations created');

  // ==================== CONTRACTS ====================

  // 1. Ejeraftale (STRENGT_FORTROLIG)
  const contractEjeraftale = await prisma.contract.create({
    data: {
      id: 'contract-ejeraftale-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.EJERAFTALE,
      displayName: 'Ejeraftale - Østerbro Klinik',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.STRENGT_FORTROLIG,
      deadlineType: DeadlineType.ABSOLUT,
      versionSource: VersionSource.CUSTOM,
      effectiveDate: new Date('2020-03-01'),
      signedDate: new Date('2020-02-15'),
      noticePeriodDays: 90,
      reminder90Days: true,
      reminder30Days: true,
      reminder7Days: true,
      reminderRecipients: [userOwner.id],
      mustRetainUntil: new Date('2030-03-01'), // 10 år jf. forældelsesloven
      typeData: {
        ownership_percentage: { [personOwner.id]: 60 },
        pre_emption_right: true,
        pre_emption_days: 30,
        drag_along: true,
        tag_along: true,
        non_compete_months: 24,
      },
      notes: 'Hovedejeraftale for klinikken',
      createdBy: userOwner.id,
    },
  });

  // 2. Lejekontrakt (INTERN)
  const contractLeje = await prisma.contract.create({
    data: {
      id: 'contract-leje-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.LEJEKONTRAKT_ERHVERV,
      displayName: 'Lejekontrakt - Østerbrogade 50',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.ABSOLUT,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      effectiveDate: new Date('2020-04-01'),
      expiryDate: null, // løbende lejemål
      signedDate: new Date('2020-03-15'),
      noticePeriodDays: 180,
      reminder90Days: true,
      reminder30Days: true,
      reminder7Days: false,
      reminderRecipients: [userOwner.id, userAdmin.id],
      mustRetainUntil: new Date('2025-12-31'), // 5 år jf. bogføringsloven
      typeData: {
        property_address: 'Østerbrogade 50, 2100 København Ø',
        monthly_rent: 45000,
        annual_rent_adjustment: 'NPI',
        auto_renewal: true,
        auto_renewal_period_yrs: 5,
        deposit_months: 6,
      },
      notes: 'Løbende lejemål med automatisk forlængelse',
      createdBy: userOwner.id,
    },
  });

  // 3. Ansættelseskontrakt (FORTROLIG)
  const contractAnsaettelse = await prisma.contract.create({
    data: {
      id: 'contract-ansaettelse-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.ANSAETTELSE_FUNKTIONAER,
      displayName: 'Ansættelseskontrakt - Anna Pedersen',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.FORTROLIG,
      deadlineType: DeadlineType.OPERATIONEL,
      versionSource: VersionSource.INTERNT,
      effectiveDate: new Date('2021-06-01'),
      signedDate: new Date('2021-05-15'),
      anciennityStart: new Date('2021-06-01'),
      noticePeriodDays: 30, // opdateres automatisk baseret på anciennitet
      reminder90Days: false,
      reminder30Days: false,
      reminder7Days: false,
      reminderRecipients: [],
      mustRetainUntil: new Date('2026-06-01'), // 5 år efter fratrædelse (antager aktiv)
      typeData: {
        probation_end_date: '2021-09-01',
        collective_agreement: null,
      },
      notes: 'Klinikassistent på fuld tid',
      createdBy: userOwner.id,
    },
  });

  // 4. Leverandørkontrakt (INTERN)
  const contractLeverandoer = await prisma.contract.create({
    data: {
      id: 'contract-leverandoer-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.LEVERANDOERKONTRAKT,
      displayName: 'IT-vedligeholdelsesaftale - TechSupport A/S',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.OPERATIONEL,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      effectiveDate: new Date('2022-01-01'),
      expiryDate: new Date('2024-12-31'),
      signedDate: new Date('2021-12-01'),
      noticePeriodDays: 90,
      reminder90Days: true,
      reminder30Days: true,
      reminder7Days: false,
      reminderRecipients: [userAdmin.id],
      mustRetainUntil: new Date('2029-12-31'), // 5 år efter udløb
      typeData: {
        vendor_name: 'TechSupport A/S',
        vendor_cvr: '11223344',
        auto_renewal: true,
        auto_renewal_days: 60,
        monthly_cost: 5000,
        annual_cost: 60000,
      },
      notes: 'IT-support og vedligeholdelse af klinikudstyr',
      createdBy: userOwner.id,
    },
  });

  // 5. Forsikring (INTERN)
  const contractForsikring = await prisma.contract.create({
    data: {
      id: 'contract-forsikring-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.FORSIKRING,
      displayName: 'Erhvervsansvarsforsikring - Tryg',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.OPERATIONEL,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      effectiveDate: new Date('2023-01-01'),
      expiryDate: new Date('2024-01-01'),
      signedDate: new Date('2022-12-15'),
      noticePeriodDays: 30,
      reminder90Days: true,
      reminder30Days: true,
      reminder7Days: true,
      reminderRecipients: [userOwner.id],
      mustRetainUntil: new Date('2029-01-01'), // 5 år efter udløb
      typeData: {
        insurance_type: 'ERHVERVSANSVAR',
        policy_number: 'POL-2023-00123',
        annual_premium: 25000,
        coverage_amount: 5000000,
      },
      notes: 'Erhvervsansvarsforsikring inkl. patientskade',
      createdBy: userOwner.id,
    },
  });

  console.log('✅ Contracts created: 5 contracts');

  // ==================== CONTRACT PARTIES ====================
  await prisma.contractParty.createMany({
    data: [
      {
        id: 'party-ejeraftale-001',
        organizationId: organization.id,
        contractId: contractEjeraftale.id,
        personId: personOwner.id,
        isSigner: true,
        roleInContract: 'ejer',
      },
      {
        id: 'party-ansaettelse-001',
        organizationId: organization.id,
        contractId: contractAnsaettelse.id,
        personId: personEmployee.id,
        isSigner: true,
        roleInContract: 'arbejdstager',
      },
      {
        id: 'party-leje-001',
        organizationId: organization.id,
        contractId: contractLeje.id,
        personId: null,
        isSigner: false,
        counterpartyName: 'Ejendomsselskabet Østerbro ApS',
        roleInContract: 'udlejer',
      },
    ],
  });
  console.log('✅ Contract parties created');

  // ==================== CONTRACT VERSIONS ====================
  await prisma.contractVersion.createMany({
    data: [
      {
        id: 'version-ejeraftale-001',
        organizationId: organization.id,
        contractId: contractEjeraftale.id,
        versionNumber: 1,
        fileUrl: '/uploads/contracts/ejeraftale-v1.pdf',
        fileName: 'ejeraftale-oesterbro-v1.pdf',
        fileSizeBytes: 245000,
        isCurrent: true,
        changeType: 'REDAKTIONEL',
        changeNote: 'Oprindelig version',
        uploadedBy: userOwner.id,
      },
      {
        id: 'version-leje-001',
        organizationId: organization.id,
        contractId: contractLeje.id,
        versionNumber: 1,
        fileUrl: '/uploads/contracts/lejekontrakt-v1.pdf',
        fileName: 'lejekontrakt-oesterbrogade-v1.pdf',
        fileSizeBytes: 380000,
        isCurrent: true,
        changeType: 'REDAKTIONEL',
        changeNote: 'Oprindelig version',
        uploadedBy: userOwner.id,
      },
    ],
  });
  console.log('✅ Contract versions created');

  // ==================== FINANCIAL METRICS ====================
  await prisma.financialMetric.createMany({
    data: [
      {
        id: 'metric-001',
        organizationId: organization.id,
        companyId: klinikCompany.id,
        metricType: MetricType.OMSAETNING,
        periodType: PeriodType.HELAAR,
        periodYear: 2023,
        value: 4500000,
        currency: 'DKK',
        source: MetricSource.REVIDERET,
        notes: 'Årsregnskab 2023',
        createdBy: userOwner.id,
      },
      {
        id: 'metric-002',
        organizationId: organization.id,
        companyId: klinikCompany.id,
        metricType: MetricType.EBITDA,
        periodType: PeriodType.HELAAR,
        periodYear: 2023,
        value: 850000,
        currency: 'DKK',
        source: MetricSource.REVIDERET,
        notes: 'Årsregnskab 2023',
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ Financial metrics created');

  // ==================== CASE ====================
  const testCase = await prisma.case.create({
    data: {
      id: 'case-001',
      organizationId: organization.id,
      title: 'Lejeforhandling 2024',
      caseType: SagsType.KONTRAKT,
      caseSubtype: 'FORHANDLING',
      status: CaseStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      description: 'Forhandling af lejevilkår ved udløb af indeværende periode',
      responsibleId: userAdmin.id,
      dueDate: new Date('2024-09-01'),
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Case created: ${testCase.title}`);

  // ==================== CASE RELATIONS (DEC-016) ====================
  await prisma.caseCompany.create({
    data: {
      organizationId: organization.id,
      caseId: testCase.id,
      companyId: klinikCompany.id,
      createdBy: userOwner.id,
    },
  });

  await prisma.caseContract.create({
    data: {
      organizationId: organization.id,
      caseId: testCase.id,
      contractId: contractLeje.id,
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Case relations created');

  // ==================== DEADLINE ====================
  await prisma.deadline.create({
    data: {
      id: 'deadline-001',
      organizationId: organization.id,
      title: 'Frist for lejeopsigelse',
      dueDate: new Date('2024-06-01'),
      priority: Prioritet.HOEJ,
      assignedTo: userAdmin.id,
      contractId: contractLeje.id,
      caseId: testCase.id,
      note: 'Opsigelse skal være udlejer i hænde senest denne dato',
      adviseDaysBefore: 14,
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Deadline created');

  // ==================== TASK ====================
  await prisma.task.create({
    data: {
      id: 'task-001',
      organizationId: organization.id,
      title: 'Forbered lejeforhandlingsoplæg',
      description: 'Udarbejd analyse af markedsleje og forbered forhandlingsstrategi',
      status: 'NY',
      dueDate: new Date('2024-05-15'),
      assignedTo: userAdmin.id,
      caseId: testCase.id,
      companyId: klinikCompany.id,
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Task created');

  // ==================== AUDIT LOG ====================
  await prisma.auditLog.create({
    data: {
      id: 'audit-001',
      organizationId: organization.id,
      userId: userOwner.id,
      action: 'CREATE',
      resourceType: 'contract',
      resourceId: contractEjeraftale.id,
      sensitivity: SensitivityLevel.STRENGT_FORTROLIG,
      changes: null,
      ipAddress: '192.168.1.1',
    },
  });
  console.log('✅ Audit log entry created');

  console.log('\n🎉 Database seed completed successfully!');
  console.log('Summary:');
  console.log('  - 1 Organization');
  console.log('  - 3 Users (owner, admin, readonly)');
  console.log('  - 2 Companies (holding + klinik)');
  console.log('  - 2 Persons');
  console.log('  - 5 Contracts (ejeraftale, leje, ansættelse, leverandør, forsikring)');
  console.log('  - 1 Case with relations');
  console.log('  - 1 Deadline');
  console.log('  - 1 Task');
  console.log('  - 2 Financial metrics');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });