/**
 * ChainHub Database Seed
 * Version: 1.2 (Repair — ASCII enum names)
 * Generated by: BA-02 (Schema-agent)
 *
 * Opretter realistisk testdata:
 * - 1 organisation (tandlægekæde)
 * - 1 gruppe
 * - 2 selskaber (holdingselskab + 1 klinik)
 * - 3 brugere (owner, admin, readonly)
 * - 5 kontrakter (ejeraftale, lejekontrakt, ansættelse, leverandør, forsikring)
 * - 2 personer (ejer, ansat)
 */

import {
  PrismaClient,
  UserRole,
  UserScope,
  ContractSystemType,
  ContractStatus,
  SensitivityLevel,
  DeadlineType,
  VersionSource,
  MetricType,
  PeriodType,
  MetricSource,
  Prioritet,
  SagsType,
  CaseStatus,
  EmploymentType,
  CompanyType,
  OwnershipType,
} from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting ChainHub database seed...');

  // ==================== ORGANIZATION ====================
  const organization = await prisma.organization.create({
    data: {
      id: 'org-chainhub-demo-001',
      name: 'Tandlægekæden ApS',
      cvr: '12345678',
      plan: 'business',
      chainStructure: true,
      createdBy: null,
    },
  });
  console.log(`✅ Organization created: ${organization.name}`);

  // ==================== GROUP ====================
  const group = await prisma.group.create({
    data: {
      id: 'group-main-001',
      organizationId: organization.id,
      name: 'Tandlægekæden Koncern',
      description: 'Primær koncerngruppe',
      createdBy: null,
    },
  });
  console.log(`✅ Group created: ${group.name}`);

  // ==================== USERS ====================
  const userOwner = await prisma.user.create({
    data: {
      id: 'user-owner-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'lars.jensen@tandlaegekaden.dk',
      name: 'Lars Jensen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userAdmin = await prisma.user.create({
    data: {
      id: 'user-admin-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'maria.nielsen@tandlaegekaden.dk',
      name: 'Maria Nielsen',
      avatarUrl: null,
      microsoftId: null,
    },
  });

  const userReadonly = await prisma.user.create({
    data: {
      id: 'user-readonly-001',
      organizationId: organization.id,
      groupId: group.id,
      email: 'peter.hansen@tandlaegekaden.dk',
      name: 'Peter Hansen',
      avatarUrl: null,
      microsoftId: null,
    },
  });
  console.log(`✅ Users created: ${userOwner.name}, ${userAdmin.name}, ${userReadonly.name}`);

  // ==================== USER ROLE ASSIGNMENTS ====================
  await prisma.userRoleAssignment.createMany({
    data: [
      {
        id: 'role-owner-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userOwner.id,
        role: UserRole.GROUP_OWNER,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-admin-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userAdmin.id,
        role: UserRole.GROUP_ADMIN,
        scope: UserScope.ALL,
        companyIds: [],
        createdBy: userOwner.id,
      },
      {
        id: 'role-readonly-001',
        organizationId: organization.id,
        groupId: group.id,
        userId: userReadonly.id,
        role: UserRole.GROUP_READONLY,
        scope: UserScope.ASSIGNED,
        companyIds: [],
        createdBy: userOwner.id,
      },
    ],
  });
  console.log('✅ User role assignments created');

  // ==================== COMPANIES ====================
  const holdingCompany = await prisma.company.create({
    data: {
      id: 'company-holding-001',
      organizationId: organization.id,
      groupId: group.id,
      cvr: '87654321',
      name: 'Tandlægekæden Holding ApS',
      companyType: CompanyType.APS,
      address: 'Holdingvej 1',
      city: 'København K',
      zip: '1000',
      country: 'DK',
      email: 'holding@tandlaegekaden.dk',
      phone: '+4512345678',
      isHolding: true,
      parentId: null,
      createdBy: userOwner.id,
    },
  });

  const klinikCompany = await prisma.company.create({
    data: {
      id: 'company-klinik-001',
      organizationId: organization.id,
      groupId: group.id,
      cvr: '11223344',
      name: 'Tandlæge Nørrebro ApS',
      companyType: CompanyType.APS,
      address: 'Nørrebrogade 100',
      city: 'København N',
      zip: '2200',
      country: 'DK',
      email: 'noerrebro@tandlaegekaden.dk',
      phone: '+4598765432',
      isHolding: false,
      parentId: holdingCompany.id,
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Companies created: ${holdingCompany.name}, ${klinikCompany.name}`);

  // ==================== OWNERSHIP ====================
  await prisma.ownership.create({
    data: {
      id: 'ownership-001',
      organizationId: organization.id,
      ownerCompanyId: holdingCompany.id,
      ownedCompanyId: klinikCompany.id,
      ownershipType: OwnershipType.DIREKTE,
      sharePercentage: 100.0,
      votingRights: 100.0,
      validFrom: new Date('2020-01-01'),
      validTo: null,
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Ownership created');

  // ==================== PERSONS ====================
  const personEjer = await prisma.person.create({
    data: {
      id: 'person-ejer-001',
      organizationId: organization.id,
      companyId: holdingCompany.id,
      firstName: 'Lars',
      lastName: 'Jensen',
      email: 'lars.jensen@tandlaegekaden.dk',
      phone: '+4512345678',
      jobTitle: 'Direktør',
      employmentType: EmploymentType.FUNKTIONAER,
      startDate: new Date('2015-01-01'),
      createdBy: userOwner.id,
    },
  });

  const personAnsat = await prisma.person.create({
    data: {
      id: 'person-ansat-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      firstName: 'Anna',
      lastName: 'Andersen',
      email: 'anna.andersen@noerrebro.dk',
      phone: '+4587654321',
      jobTitle: 'Tandlæge',
      employmentType: EmploymentType.FUNKTIONAER,
      startDate: new Date('2021-03-01'),
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Persons created: ${personEjer.firstName} ${personEjer.lastName}, ${personAnsat.firstName} ${personAnsat.lastName}`);

  // ==================== CONTRACTS ====================
  const contractEjeraftale = await prisma.contract.create({
    data: {
      id: 'contract-ejeraftale-001',
      organizationId: organization.id,
      companyId: holdingCompany.id,
      systemType: ContractSystemType.EJERAFTALE,
      displayName: 'Ejeraftale — Tandlægekæden Holding ApS',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.STRENGT_FORTROLIG,
      deadlineType: DeadlineType.INGEN,
      signedDate: new Date('2020-01-15'),
      startDate: new Date('2020-01-15'),
      versionSource: VersionSource.INTERNT,
      counterpartyName: 'Lars Jensen',
      createdBy: userOwner.id,
    },
  });

  const contractLejekontrakt = await prisma.contract.create({
    data: {
      id: 'contract-lejekontrakt-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.LEJEKONTRAKT_ERHVERV,
      displayName: 'Lejekontrakt — Nørrebrogade 100',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.ABSOLUT,
      signedDate: new Date('2021-01-01'),
      startDate: new Date('2021-01-01'),
      endDate: new Date('2026-12-31'),
      noticePeriodDays: 180,
      autoRenew: false,
      versionSource: VersionSource.BRANCHESTANDARD,
      counterpartyName: 'Ejendomsselskabet Nørrebro A/S',
      counterpartyCvr: '55667788',
      createdBy: userOwner.id,
    },
  });

  const contractAnsaettelse = await prisma.contract.create({
    data: {
      id: 'contract-ansaettelse-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      personId: personAnsat.id,
      systemType: ContractSystemType.ANSAETTELSE_FUNKTIONAER,
      displayName: 'Ansættelseskontrakt — Anna Andersen',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.FORTROLIG,
      deadlineType: DeadlineType.INGEN,
      signedDate: new Date('2021-02-15'),
      startDate: new Date('2021-03-01'),
      versionSource: VersionSource.BRANCHESTANDARD,
      counterpartyName: 'Anna Andersen',
      createdBy: userOwner.id,
    },
  });

  const contractLeverandoer = await prisma.contract.create({
    data: {
      id: 'contract-leverandoer-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.LEVERANDOERKONTRAKT,
      displayName: 'Leverandørkontrakt — Dental Supply A/S',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.STANDARD,
      deadlineType: DeadlineType.OPERATIONEL,
      signedDate: new Date('2022-06-01'),
      startDate: new Date('2022-07-01'),
      noticePeriodDays: 90,
      autoRenew: true,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      counterpartyName: 'Dental Supply A/S',
      counterpartyCvr: '99887766',
      createdBy: userAdmin.id,
    },
  });

  const contractForsikring = await prisma.contract.create({
    data: {
      id: 'contract-forsikring-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      systemType: ContractSystemType.FORSIKRING,
      displayName: 'Erhvervsansvarsforsikring 2024',
      status: ContractStatus.AKTIV,
      sensitivity: SensitivityLevel.INTERN,
      deadlineType: DeadlineType.ABSOLUT,
      signedDate: new Date('2024-01-01'),
      startDate: new Date('2024-01-01'),
      endDate: new Date('2025-01-01'),
      autoRenew: true,
      versionSource: VersionSource.EKSTERNT_STANDARD,
      counterpartyName: 'Tryg Forsikring A/S',
      createdBy: userAdmin.id,
    },
  });
  console.log(`✅ Contracts created: ${contractEjeraftale.displayName}, ${contractLejekontrakt.displayName}, ${contractAnsaettelse.displayName}, ${contractLeverandoer.displayName}, ${contractForsikring.displayName}`);

  // ==================== CONTRACT TYPE DETAILS ====================
  await prisma.contractTypeDetail.create({
    data: {
      id: 'ctd-lejekontrakt-001',
      contractId: contractLejekontrakt.id,
      organizationId: organization.id,
      leaseType: 'OPERATIONEL',
      leaseArea: 250.0,
      leaseMonthlyRent: 45000.0,
      leaseDepositMonths: 3,
      leaseRegulationClause: 'Nettoprisindeks',
      createdBy: userOwner.id,
    },
  });

  await prisma.contractTypeDetail.create({
    data: {
      id: 'ctd-ansaettelse-001',
      contractId: contractAnsaettelse.id,
      organizationId: organization.id,
      employmentType: EmploymentType.FUNKTIONAER,
      salary: 65000.0,
      workingHours: 37.0,
      nonCompeteMonths: 12,
      nonSolicitMonths: 6,
      noticePeriodEmployee: 3,
      noticePeriodEmployer: 6,
      createdBy: userOwner.id,
    },
  });

  await prisma.contractTypeDetail.create({
    data: {
      id: 'ctd-forsikring-001',
      contractId: contractForsikring.id,
      organizationId: organization.id,
      insuranceType: 'ERHVERVSANSVAR',
      insurancePremium: 24000.0,
      insuranceCoverage: 5000000.0,
      createdBy: userAdmin.id,
    },
  });
  console.log('✅ Contract type details created');

  // ==================== FINANCIAL METRICS ====================
  await prisma.financialMetric.createMany({
    data: [
      {
        id: 'metric-omsaetning-2023',
        organizationId: organization.id,
        companyId: klinikCompany.id,
        metricType: MetricType.OMSAETNING,
        periodType: PeriodType.HELAER,
        periodYear: 2023,
        value: 4850000.0,
        currency: 'DKK',
        source: MetricSource.REVIDERET,
        createdBy: userAdmin.id,
      },
      {
        id: 'metric-ebitda-2023',
        organizationId: organization.id,
        companyId: klinikCompany.id,
        metricType: MetricType.EBITDA,
        periodType: PeriodType.HELAER,
        periodYear: 2023,
        value: 1250000.0,
        currency: 'DKK',
        source: MetricSource.REVIDERET,
        createdBy: userAdmin.id,
      },
    ],
  });
  console.log('✅ Financial metrics created');

  // ==================== CASE ====================
  const sag = await prisma.case.create({
    data: {
      id: 'case-gdpr-001',
      organizationId: organization.id,
      companyId: klinikCompany.id,
      sagsType: SagsType.COMPLIANCE,
      sagsSubtype: 'GDPR',
      title: 'GDPR-gennemgang 2024',
      description: 'Årlig GDPR-compliance gennemgang for Tandlæge Nørrebro ApS',
      status: CaseStatus.AKTIV,
      sensitivity: SensitivityLevel.FORTROLIG,
      prioritet: Prioritet.NORMAL,
      assignedTo: userAdmin.id,
      dueDate: new Date('2024-06-30'),
      createdBy: userOwner.id,
    },
  });
  console.log(`✅ Case created: ${sag.title}`);

  // ==================== TASK ====================
  await prisma.task.create({
    data: {
      id: 'task-gdpr-001',
      organizationId: organization.id,
      caseId: sag.id,
      companyId: klinikCompany.id,
      title: 'Opdater behandlingsfortegnelse',
      description: 'Gennemgå og opdater register over behandlingsaktiviteter iht. GDPR art. 30',
      status: 'NY',
      prioritet: Prioritet.HOEJ,
      assignedTo: userAdmin.id,
      dueDate: new Date('2024-04-30'),
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Task created');

  // ==================== ACTIVITY LOG ====================
  await prisma.activityLog.create({
    data: {
      id: 'activity-001',
      organizationId: organization.id,
      userId: userOwner.id,
      entitet: 'KONTRAKT',
      entitetId: contractEjeraftale.id,
      handling: 'OPRETTET',
      metadata: { note: 'Initial seed' },
      createdBy: userOwner.id,
    },
  });
  console.log('✅ Activity log created');

  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });