import type { ContractSystemType } from '@prisma/client'

// Danske labels for alle 34 kontrakttyper
export const CONTRACT_TYPE_LABELS: Record<ContractSystemType, string> = {
  // Lag 1 — Universelle
  EJERAFTALE: 'Ejeraftale',
  DIREKTOERKONTRAKT: 'Direktørkontrakt',
  OVERDRAGELSESAFTALE: 'Overdragelsesaftale',
  AKTIONERLAN: 'Aktionærlåneaftale',
  PANTSAETNING: 'Pantsætningsaftale',
  VEDTAEGTER: 'Vedtægter',
  ANSAETTELSE_FUNKTIONAER: 'Ansættelseskontrakt (funktionær)',
  ANSAETTELSE_IKKE_FUNKTIONAER: 'Ansættelseskontrakt (ikke-funktionær)',
  VIKARAFTALE: 'Vikaraftale',
  UDDANNELSESAFTALE: 'Uddannelsesaftale',
  FRATRAEDELSESAFTALE: 'Fratrædelsesaftale',
  KONKURRENCEKLAUSUL: 'Konkurrenceklausulaftale',
  PERSONALEHÅNDBOG: 'Personalehåndbog',
  LEJEKONTRAKT_ERHVERV: 'Erhvervslejekontrakt',
  LEASINGAFTALE: 'Leasingaftale',
  LEVERANDOERKONTRAKT: 'Leverandørkontrakt',
  SAMARBEJDSAFTALE: 'Samarbejdsaftale',
  NDA: 'Fortrolighedsaftale (NDA)',
  IT_SYSTEMAFTALE: 'IT-/Systemaftale',
  DBA: 'Databehandleraftale',
  FORSIKRING: 'Forsikringsaftale',
  GF_REFERAT: 'Generalforsamlingsreferat',
  BESTYRELSESREFERAT: 'Bestyrelsesreferat',
  FORRETNINGSORDEN: 'Forretningsorden',
  DIREKTIONSINSTRUKS: 'Direktionsinstruks',
  VOA: 'Virksomhedsoverdragelsesaftale',
  // Lag 2 — Strukturtyper
  INTERN_SERVICEAFTALE: 'Intern serviceaftale',
  ROYALTY_LICENS: 'Royalty-/Licensaftale',
  OPTIONSAFTALE: 'Optionsaftale',
  TILTRAEDELSESDOKUMENT: 'Tiltrædelsesdokument',
  KASSEKREDIT: 'Kassekreditaftale',
  CASH_POOL: 'Cash pool-aftale',
  INTERCOMPANY_LAN: 'Intercompany-lån',
  SELSKABSGARANTI: 'Selskabsgaranti',
}

// Gruppe per kategori (til UI-visning)
export const CONTRACT_TYPE_CATEGORIES = {
  'Ejerskab og selskabsret': [
    'EJERAFTALE',
    'DIREKTOERKONTRAKT',
    'OVERDRAGELSESAFTALE',
    'AKTIONERLAN',
    'PANTSAETNING',
    'VEDTAEGTER',
  ] as ContractSystemType[],
  'Ansættelse og personale': [
    'ANSAETTELSE_FUNKTIONAER',
    'ANSAETTELSE_IKKE_FUNKTIONAER',
    'VIKARAFTALE',
    'UDDANNELSESAFTALE',
    'FRATRAEDELSESAFTALE',
    'KONKURRENCEKLAUSUL',
    'PERSONALEHÅNDBOG',
  ] as ContractSystemType[],
  'Lokaler og udstyr': [
    'LEJEKONTRAKT_ERHVERV',
    'LEASINGAFTALE',
  ] as ContractSystemType[],
  'Kommercielle aftaler': [
    'LEVERANDOERKONTRAKT',
    'SAMARBEJDSAFTALE',
    'NDA',
    'IT_SYSTEMAFTALE',
    'DBA',
  ] as ContractSystemType[],
  'Forsikring og governance': [
    'FORSIKRING',
    'GF_REFERAT',
    'BESTYRELSESREFERAT',
    'FORRETNINGSORDEN',
    'DIREKTIONSINSTRUKS',
    'VOA',
  ] as ContractSystemType[],
  'Kædestruktur (Lag 2)': [
    'INTERN_SERVICEAFTALE',
    'ROYALTY_LICENS',
    'OPTIONSAFTALE',
    'TILTRAEDELSESDOKUMENT',
    'KASSEKREDIT',
    'CASH_POOL',
    'INTERCOMPANY_LAN',
    'SELSKABSGARANTI',
  ] as ContractSystemType[],
}